[[main]]
  name = "GitHub"
  url = "https://github.com/h-enk/hyas"
  weight = 10

[[social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/henkverlinde/"
  weight = 10

[[social]]
  name = "Twitter"
  url = "https://twitter.com/henkverlinde"
  weight = 20

[[docs]]
  name = "About Hyas"
  weight = 1
  identifier = "about-hyas"
  url = "/docs/about-hyas/"

[[docs]]
  name = "Getting Started"
  weight = 5
  identifier = "getting-started"
  url = "/docs/getting-started/"
