title = "Hyas"
titleSeparator = "-"
titleAddition = "Modern Hugo Starter"
description = "Hyas is a Hugo starter helping you build modern websites that are secure, fast, and SEO-ready — by default."
images = ["hyas.png"]
twitterSite = "henkverlinde"
twitterCreator = "henkverlinde"
facebookAuthor = "verlinde.henk"
facebookPublisher = "verlinde.henk"
ogLocale = "en_US"
schemaType = "Organization"
schemaLogo = "logo-hyas.png"
schemaTwitter = "https://twitter.com/henkverlinde"
schemaLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaGitHub = "https://github.com/h-enk"
schemaSection = "blog"
siteLinksSearchBox = false

themeColor = "#fff"

quality = 85
bgColor = "#fff"
landscapePhotoWidths = [1000, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

footer = "An open source project by <a href=\"https://twitter.com/henkverlinde\" target=\"_blank\" rel=\"noopener\">@HenkVerlinde</a>"

alert = false
alertText = "⭐️ If you like Hyas, give it a star on <a class=\"alert-link\" href=\"https://github.com/h-enk/hyas\" target=\"_blank\" rel=\"noopener\">GitHub</a>! ⭐️" 

hyasVersion = "v1.2.6"

docsRepo = "https://github.com/h-enk/gethyas.com/"
