[build]
  publish = "public"
  functions = "functions"
  command = "hugo --gc --minify && npm run build:functions"

[build.environment]
  HUGO_VERSION = "0.74.3"
  NODE_VERSION = "13.11.0"
  NPM_VERSION = "6.13.7"
  YARN_VERSION = "1.22.4"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
