[build]
  publish = "public"
  functions = "functions"

[build.environment]
  HUGO_VERSION = "0.74.3"
  NODE_VERSION = "13.11.0"
  NPM_VERSION = "6.13.7"
  YARN_VERSION = "1.22.4"

[context.production]
  command = "yarn build --config config/production/config.toml"

[context.deploy-preview]
  command = "yarn build --config config/staging/config.toml"

[context.branch-deploy]
  command = "yarn build -b $DEPLOY_PRIME_URL"
