[build]
  publish = "public"
  command = "yarn build"
  functions = "functions"

[build.environment]
  HUGO_VERSION = "0.74.2"
  NODE_VERSION = "13.11.0"
  NPM_VERSION = "6.13.7"
  YARN_VERSION = "1.22.4"

[context.deploy-preview]
  command = "yarn build:preview -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "yarn build -b $DEPLOY_PRIME_URL"