[build]
  publish = "public"
  functions = "functions"
  command = "hugo --gc --minify && npm run build:functions"

[context.production.environment]
  HUGO_VERSION = "0.74.3"
  NODE_VERSION = "13.11.0"
  NPM_VERSION = "6.13.7"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.74.3"
  NODE_VERSION = "13.11.0"
  NPM_VERSION = "6.13.7"
  HUGO_ENV = "staging"

[context.branch-deploy]
  command = "hugo --gc --minify"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.74.3"
  NODE_VERSION = "13.11.0"
  NPM_VERSION = "6.13.7"
  HUGO_ENV = "staging"
