[build]
  publish = "public/"
  command = "yarn build"
  functions = "functions/"

[build.environment]
  HUGO_VERSION = "0.62.2"
  NODE_VERSION = "10.16.0"
  NPM_VERSION = "6.9.0"
  YARN_VERSION = "1.21.1"

[context.deploy-preview]
  command = "yarn build:preview"

[context.branch-deploy]
  command = "yarn build"
